### ISSUE TITLE
[DevOps] Could NOT find PythonInterp: Found unsuitable version "1.4", but required is at least "2"

### ISSUE THREAD

**Issue by seanyen** [ms-iot/ROSOnWindows#124]
**Describe the bug**
By using Azure DevOps pipelines for CI, I added the steps like below:
```yaml
jobs:
- job: Build
  pool:
    vmImage: 'vs2017-win2016'
  timeoutInMinutes: 240
  steps:
  - script: |
      choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
      choco upgrade ros-melodic-ros_core -y
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\setup.bat"
      pushd "%Build_StagingDirectory%\catkin_ws"
      catkin_make_isolated --only-pkg-with-deps xyz --install
```

Then, when I kicked off a build, this error shows up:
```
-- This workspace overlays: C:/opt/ros/melodic/x64
CMake Error at C:/opt/rosdeps/x64/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "2" (found C:/ProgramData/chocolatey/bin/python2.exe)
```

**Expected behavior**
Kick off a DevOps build without this error.
