### ISSUE TITLE
[Humble] Support MicroROS2 Agent on Windows

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#381]
ROS Distro: `humble`

**Describe the need**
MicroROS2 is a ROS package for interfacing with Microcontrollers.

**Sources**
``` yaml
repositories:
  micro_ros_msgs:
    type: git
    url: https://github.com/micro-ROS/micro_ros_msgs.git
    version: humble
  micro-ROS-Agent:
    type: git
    url: https://github.com/micro-ROS/micro-ROS-Agent.git
    version:humble
```

**Should this be included in the Microsoft distribution?**
Yes, it is ubiquitous for Microcontrollers.
